name: kennzeichen
description: "Sammeln von Kfz Kennzeichen."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.1
  url_launcher: ^6.2.5
  system_theme: ^2.3.1
  intl: ^0.19.0
  package_info_plus: ^6.0.0
  shared_preferences: ^2.2.3
  flutter_settings_ui: ^3.0.1
  sqflite: ^2.3.2
  path: ^1.9.0
  maps_launcher: ^2.2.1
  flutter_expandable_fab: ^2.0.0
  scrollview_observer: ^1.19.1
  badges: ^3.1.2
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - data-scraper/data/
